# -*- coding: utf-8 -*-
"""👨‍💻 Beginner Python Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1F11RupdgMagDbGwEjL99piWWjRg4g1vs
"""

# 🎮 Wall Rabbit Arrow Game

import random

'''
1 for .
2 for Rabbit
3 for Arrow
'''
computer = random.choice([1,2,3])
yourstr = input("Enter your choice: ")

youDic = {
    "w": 1,
    "r": 2,
    "a": 3
}
reverseDic = {
    1: "Wall",
    2: "Rabbit",
    3: "Arrow"
}

you = youDic.get(yourstr)

print(f"You choose {reverseDic[you]}")
print(f"Computer choose {reverseDic[computer]}")

if(computer == you):
    print("It's Draw")

else:
    if(computer ==1 and you == 2):
        print("Your Win")

    elif(computer ==1 and you == 3):
        print("Computer Win")

    elif(computer ==2 and you == 1):
        print("Computer Win")

    elif(computer ==2 and you == 3):
        print("Your Win")

    elif(computer ==3 and you == 1):
        print("Your Win")

    elif(computer ==3 and you == 2):
        print("Computer Win")

    else:
        print("Something went wrong!")

"""
w for Wall

r for Rabbit

a for Arrow
"""